## **Exercises**

#### Exercise 1: Import the numpy package under the name np

In [26]:
# Your Code Here
import numpy as np

#### Exercise 2: Given an array *X*. Calculate sine, cosine, and tangent of *X*, element-wise.

X = np.array([1, 45, 60, 90])

In [27]:
# Your Code Here
X = np.array([1, 45, 60, 90])
sin = np.sin(X * np.pi / 180)
cos = np.cos(X * np.pi / 180)
tan = np.tan(X * np.pi / 180)

print(sin)
print(cos)
print(tan)

[0.01745241 0.70710678 0.8660254  1.        ]
[9.99847695e-01 7.07106781e-01 5.00000000e-01 6.12323400e-17]
[1.74550649e-02 1.00000000e+00 1.73205081e+00 1.63312394e+16]


#### Exercise 3: Given an array *X*. Convert angles from radians to degrees.

X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

In [28]:
# Your Code Here
X = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
degree = np.degrees(X)
degree

array([-180.,  -90.,   90.,  180.])

#### Exercise 4: Given an arrya *X*. Convert angles from degrees to radians.

X = np.array([-180.,  -90.,   90.,  180.])

In [29]:
# Your Code Here
X = np.array([-180., -90., 90., 180.])
radian = np.radians(X)
radian

array([-3.14159265, -1.57079633,  1.57079633,  3.14159265])

#### Exercise 5: Given an array *X*. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of *X*, element-wise. 

X = np.array([-1., 0, 1.])

In [30]:
# Your Code Here
X = np.array([-1., 0, 1.])
sinh = np.sinh(X * np.pi / 180)
cosh = np.cosh(X * np.pi / 180)
tanh = np.tanh(X * np.pi / 180)
print(sinh)
print(cosh)
print(tanh)

[-0.01745418  0.          0.01745418]
[1.00015231 1.         1.00015231]
[-0.01745152  0.          0.01745152]


#### Exercise 6: Given an array *X*. Calculate the round, ceil, floor of *X*, element-wise

X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])

In [31]:
# Your Code Here
X = np.array([4.1, 2.5, 44.5, 25.9, -1.1, -9.5, -6.9])
round = np.around(X)
floor = np.floor(X)
ceil = np.ceil(X)
print(round)
print(floor)
print(ceil)

[  4.   2.  44.  26.  -1. -10.  -7.]
[  4.   2.  44.  25.  -2. -10.  -7.]
[ 5.  3. 45. 26. -1. -9. -6.]


#### Exercise 7: Given an array *X*. Calculate the difference between neighboring elements, element-wise.

X = np.array([11, 13, 23, 45, 77])

In [32]:
# Your Code Here
X = np.array([11, 13, 23, 45, 77])
print("Original array: ")
print(X)

print("Difference between neighboring elements, element-wise of the array")
print(np.diff(X))

Original array: 
[11 13 23 45 77]
Difference between neighboring elements, element-wise of the array
[ 2 10 22 32]


#### Exercise 8: Given two arrays *X* and *Y*. Find the cross product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [33]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
cross = np.cross(X,Y)
cross

array([-3,  6, -3])

#### Exercise 9: Given two arrays *X* and *Y*. Find the dot product.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [34]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
dot = np.dot(X,Y)
dot

32

#### Exercise 10: Given two arrays *X* and *Y*. Divide *X* by *Y* element-wise using divide, true_divide, floor_divide functions.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [35]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

divide = np.divide(X,Y)
true_divide = np.true_divide(X,Y)
floor_divide = np.floor_divide(X,Y)

print(divide)
print(true_divide)
print(floor_divide)


[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]
[0 0 0]


#### Exercise 11: Given two arrays *X* and *Y*. Compute $X^Y$, element-wise.

X = np.array([1, 2, 3])

Y = np.array([4, 5, 6])

In [36]:
# Your Code Here
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

power = np.power(X,Y)
power

array([  1,  32, 729])

#### Exercise 12: Given one array *X* and Y = 3. Compute the remainder of X / Y element-wise using remainder and fmod functions.


X = np.array([1, 2, 3])

In [37]:
# Your Code Here
print(np.remainder(X, 3))
print(np.fmod(X,3))

[1 2 0]
[1 2 0]


#### Exercise 13:  Given an array *X*. If an element of *X* is smaller than 5, replace it with 4. And if an element of *X* is bigger than 9, replace it with 8.

X = np.array([8, 4, 22, 3, 66, 12, 1, 5])

In [38]:
# Your Code Here
x = np.array([8, 4, 22, 3, 66, 12, 1, 5])

#### Exercise 14: Given an array *X*. Compute the square of *X*, element-wise.

X = np.array([2, 3, 4, 5, 6])

In [39]:
# Your Code Here
X = np.array([2, 3, 4, 5, 6])
np.square(X)

array([ 4,  9, 16, 25, 36])

#### Exercise 15: Given an array *X*. Compute the absolute value of *X*.

X = np.array([[-44, 3], [4, -3]])

In [40]:
X = np.array([[-44, 3], [4, -3]])
np.absolute(X)

array([[44,  3],
       [ 4,  3]])

#### Exercise 16: Given an array *X*. Compute an element-wise indication of the sign of *X*, element-wise.

X = np.array([1, 3, 0, -1, -3])

In [41]:
# Your Code Here
X = np.array([1, 3, 0, -1, -3])
np.sign(X)

array([ 1,  1,  0, -1, -1])

#### Exercise 17: Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [42]:
# Your Code Here
np.random.rand(4,2)

array([[0.48564257, 0.21513475],
       [0.46168657, 0.32536923],
       [0.4729023 , 0.44211934],
       [0.89100583, 0.74327435]])

#### Exercise 18: Given an array *gaussian*. How do you get the number of dimensions of the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [43]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.ndim


3

#### Exercise 19: Given an array *gaussian*. How do you get the shape of an array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [44]:
# Your Code Here

gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.shape

(2, 3, 4)

#### Exercise 20: Given an array *gaussian*. How do you get the total number of elements in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [45]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.size

24

#### Exercise 21: Given an array *gaussian*. How do you get memory consumed by each item in the array?


gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))

In [46]:
# Your Code Here
gaussian = np.random.randn(2 * 3 * 4).reshape((2, 3, 4))
gaussian.nbytes

192

#### Exercise 22: Given an array *twenty*. How do you access first two rows and three columns

twenty = (np.arange(4 * 5)).reshape(4, 5)

In [47]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
twenty[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

#### Exercise 23: Given an array *twenty*. How do you reverse the order of elements along columns?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [48]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.fliplr(twenty)

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

#### Exercise 24: Given an array *twenty*. How do you reverse the order of elements along rows?


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [49]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.flipud(twenty)

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

#### Exercise 25: Given an array *twenty*. How do you shuffle the array along axis - 0


twenty = (np.arange(4 * 5)).reshape(4, 5) 

In [50]:
# Your Code Here
twenty = (np.arange(4 * 5)).reshape(4, 5)
np.random.shuffle(twenty)
twenty

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])